ALTER TABLE companies ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS unsubscribed_at TIMESTAMPTZ;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ;
