CREATE INDEX IF NOT EXISTS idx_audit_log_action_prefix ON audit_log(action varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS idx_companies_email_lower ON companies(LOWER(email));
CREATE INDEX IF NOT EXISTS idx_campaigns_is_active ON campaigns(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_email_queue_created_at ON email_queue(created_at);
CREATE INDEX IF NOT EXISTS idx_companies_campaign_id ON companies(campaign_id) WHERE campaign_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_email_queue_company_id ON email_queue(company_id);
CREATE INDEX IF NOT EXISTS idx_users_email_lower ON users(LOWER(email));
CREATE INDEX IF NOT EXISTS idx_followup_sequences_active_step ON followup_sequences(is_active, step_order) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_email_queue_sending_updated ON email_queue(status, updated_at) WHERE status = 'sending';
CREATE INDEX IF NOT EXISTS idx_email_events_subscriber_null_company ON email_events(subscriber_id) WHERE company_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_telegram_pairs_chat_id ON telegram_pairs(chat_id) WHERE chat_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_telegram_pairs_code ON telegram_pairs(code) WHERE paired = false;
CREATE INDEX IF NOT EXISTS idx_magic_links_user_used_created ON magic_links(user_id, used_at, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_magic_links_expires ON magic_links(expires_at);
CREATE INDEX IF NOT EXISTS idx_companies_bozza_not_true ON companies(bozza_creata) WHERE bozza_creata IS NOT TRUE;
CREATE INDEX IF NOT EXISTS idx_companies_approvato_not_true ON companies(approvato) WHERE approvato IS NOT TRUE;
CREATE INDEX IF NOT EXISTS idx_companies_inviato_not_true ON companies(inviato) WHERE inviato IS NOT TRUE;
CREATE INDEX IF NOT EXISTS idx_users_status_name ON users(status, name) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_email_queue_failed_company_id ON email_queue_failed(company_id) WHERE company_id IS NOT NULL;
